=== RazorVlad/EPAMSummaryTask3/test/input.xsd
<?xml version="1.1" encoding="utf-8"?>
<!--  XML schema WO target namespace -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="Planes">
		<xsd:complexType>
			<xsd:sequence>
					<xsd:element name="Plane" type="tns:Plane" maxOccurs="unbounded"/>
			</xsd:sequence>		
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="Plane">
		<xsd:sequence>
			<xsd:element name="model" type="tns:model" />
			<xsd:element name="origin" type="xsd:string" />
			<xsd:element name="chars" type="tns:chars" />
			<xsd:element name="parameters" type="tns:parameters" />
			<xsd:element name="price" type="tns:price" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="model">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z]+-[0-9]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="chars">
		<xsd:sequence>
			<xsd:element name="type" type="tns:type" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="places" type="tns:places" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="ammo" type="tns:ammo" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="radar" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="places">
		<xsd:restriction base="xsd:byte">
			<xsd:minInclusive value="1"/>
		 	<xsd:maxInclusive value="2"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="ammo">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="rocket" type="tns:rocket"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:simpleType name="rocket">
		<xsd:restriction base="xsd:byte">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="parameters">
		<xsd:sequence>
			<xsd:element name="length" type="xsd:double" />
			<xsd:element name="width" type="xsd:double" />
			<xsd:element name="height" type="xsd:double" />
		</xsd:sequence>
		<xsd:attribute name="unit" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="price">
		<xsd:simpleContent>
			<xsd:extension base="xsd:double">
				<xsd:attribute name="unit" type="xsd:string"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:simpleType name="type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Support"/>
			<xsd:enumeration value="Escort"/>
			<xsd:enumeration value="Fighter"/>
			<xsd:enumeration value="Interceptor"/>
			<xsd:enumeration value="Scout"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== RazorVlad/EPAMSummaryTask3/input.xml
<?xml version="1.0" encoding="utf-8"?>
<!--  Input XML document. This XML is valid against input.xsd XML schema-->

<st3:Planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:st3="http://nure.ua/kramarenko/SummaryTask3/entity"
		xsi:schemaLocation="http://nure.ua/kramarenko/SummaryTask3/entity input.xsd">

	<Plane>
		<model>MIG-29</model>
		<origin>USSR</origin>
		<chars>
			<type>Fighter</type>
			<places>2</places>
			<ammo rocket="7">true</ammo>
			<radar>true</radar>
		</chars>
		<parameters unit="metres"> 
			<length>17.32</length>
			<width>11.36</width>
			<height>4.73</height>
		</parameters>
		<price unit="taller">100000</price>
	</Plane>
	
	<Plane>
	<model>AN-30</model>
	<origin>USSR</origin>
	<chars>
		<type>Support</type>
		<places>2</places>
		<ammo>false</ammo>
		<radar>true</radar>
	</chars>
	<parameters unit="metres"> 
		<length>24.26</length>
		<width>29.2</width>
		<height>8.32</height>
	</parameters>
	<price unit="taller">900000</price>
	</Plane>
		<Plane>
	<model>F-4</model>
	<origin>USA</origin>
	<chars>
		<type>Fighter</type>
		<places>1</places>
		<ammo rocket="10">true</ammo>
		<radar>true</radar>
	</chars>
	<parameters unit="metres"> 
		<length>400 </length>
		<width>500</width>
		<height>50</height>
	</parameters>
	<price unit="taller">500000</price>
	</Plane>
	
	<Plane>
	<model>CU-27</model>
	<origin>USSR</origin>
	<chars>
		<type>Fighter</type>
		<places>1</places>
		<ammo rocket="5">true</ammo>
		<radar>true</radar>
	</chars>
	<parameters unit="metres"> 
		<length>21.935</length>
		<width>14.698</width>
		<height>5.9</height>
	</parameters>
	<price unit="taller">300000</price>
	</Plane>
	
	<Plane>
	<model>F-22</model>
	<origin>USA</origin>
	<chars>
		<type>Fighter</type>
		<places>1</places>
		<ammo rocket="10">true</ammo>
		<radar>true</radar>
	</chars>
	<parameters unit="metres"> 
		<length>18.9</length>
		<width>13.56</width>
		<height>5.09</height>
	</parameters>
	<price unit="taller">100000000</price>
	</Plane>
	
</st3:Planes>

=== RazorVlad/EPAMSummaryTask3/test/wrongInputTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--  Input XML document. This XML is valid against input.xsd XML schema-->

<st3:Planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:st3="http://nure.ua/kramarenko/SummaryTask3/entity"
		xsi:schemaLocation="http://nure.ua/kramarenko/SummaryTask3/entity input.xsd">

	<Plane>
		<model>QWERTY-123</model>
		<origin>UA</origin>
		<chars>
			<type>Fighter</type>
			<places>2</places>
			<ammo>false</ammo>
			<radar>true</radar>
		</chars>
		<parameters unit="metres"> 
			<length>400 </length>
			<width>500</width>
			<height>50</height>
		</parameters>
		<price unit="rub">100000</price>
	</Plane>
	
	<Plane>
	<model>B-52</model>
	<origin>USA</origin>
	<chars>
		<type>Fighter</type>
		<places>1</places>
		<ammo rocket="10">true</ammo>
		<radar>true</radar>
	</chars>
	<parameters unit="metres"> 
		<length>400 </length>
		<width>500</width>
		<height>50</height>
	</parameters>
	<price unit="$">100000</price>
	</Plane>
	
</st3:Planes>
